[tools]
usage = "latest"
kubectl = "latest"
awscli = "latest"
helm = "latest"
helmfile = "latest"
sops = "latest"
terraform = "latest"
ruby = "latest"
k9s = "latest"
aws-iam-authenticator = "latest"
go = "latest"
minikube = "latest"
kube-score = "latest"
just = "latest"
krew = "latest"
task = "latest"
amazon-ecr-credential-helper = "latest"
helm-diff = "latest"
kubeconform = "latest"
kind = "latest"
poetry = "latest"
glab = "latest"
zig = "latest"
dive = "latest"
python = "latest"
"pipx:pynitrokey" = "latest"
node = "latest"

[settings]
experimental = true
legacy_version_file = false

[env]
DOCKER_HOST = "unix://{{env.XDG_RUNTIME_DIR}}/docker.sock"
